### ISSUE TITLE
Encode error

### ISSUE THREAD

**Issue by apcloic** [e-shulitsky/adeezer#3]
Hi,

I'm playing with your script right now ;)
It works very well but give the following error with some albums (e.g. ID 7311881)

Traceback (most recent call last):
  File "adeezer.py", line 127, in <module>
    tracks, download_dir = get_tracks('album', item_id,)
  File "adeezer.py", line 61, in get_tracks
    print check_name
  File "C:\adeezer\env\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 31-32: character maps to <undefined>

Regards,

**Comment by jsnjack** [comment]
Thank you for creating this issue. It is only Windows specific. Should be fixed now

**Comment by apcloic** [comment]
Hi,
I can confirm that issue is solved, thanks to your fix ;)
Regards,
