### ISSUE TITLE
Can't resume if songs' name contains special characters

### ISSUE THREAD

**Issue by apcloic** [e-shulitsky/adeezer#4]
Hi,

Env : Windows

When trying to resume, it fails with the following issue if there is a song name that contains special characters (ie single quote, ø, ...)

Traceback (most recent call last):
  File "adeezer.py", line 130, in <module>
    tracks, download_dir = get_tracks('playlist', item_id)
  File "adeezer.py", line 50, in get_tracks
    file_list = [x.decode("utf-8") for x in os.listdir(download_dir)]
  File "C:\adeezer\env\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 5: invalid start byte

So, as a workaround I've temporarly modifying charset at the following line :
file_list = [x.decode("iso-8859-1") for x in os.listdir(download_dir)]

Regards,

**Comment by jsnjack** [comment]
hey, could you please give me the way to reproduce the issue?

**Comment by apcloic** [comment]
yes, for sure.
Try downloading playlist with ID 56717947.
At first, it will properly start downloading some files but if something went wrong so you have to resume downloading and if in this playlist you already download a song with title or artist name containing any special characters (for example track with ID 10023508), then it fails & ends with the traceback that I've posted.
'hope it helps.
Regards,

**Comment by apcloic** [comment]
Works great, thanks !
Regards,

**Comment by jsnjack** [comment]
You are welcome!
